backend:
  name: git-gateway
  branch: main
  site_url: https://majestic-pothos-e3649b.netlify.app

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/home.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/about.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/issues.md"
        label: "Issues"
        name: "issues"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}