backend:
  name: github
  repo: elek5555/teamlarson.github.io
  branch: main
  auth_type: token
  token: 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

media_folder: "images/uploads"
public_folder: "/images/uploads"

site_url: https://majestic-pothos-e3649b.netlify.app

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "About Page"
        name: "about"
        file: "about.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "Issues Page"
        name: "issues"
        file: "issues.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "Contact Page"
        name: "contact"
        file: "contact.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

